_target_: src.inference.iterative.IterativeGuide
_partial_: true
guide:
  _target_: src.inference.auto_mean_field.AutoMeanFieldProposal
  _partial_: true
optim:
  _target_: optax.yogi
  learning_rate: 1e-4
tracer:
  _target_: src.inference.graphical.OnlineVarGradTracer
  num_particles: 10
num_iterations: 100
