_target_: src.trainer.batchvi.BatchVariationalPara

local_optim:
  _target_: optax.adam
  learning_rate: 1e-3
optim:
  _target_: optax.adam
  learning_rate: 1e-3
rng: 123
tracer:
  _target_: src.inference.graphical.ELBOTracer
  num_particles: 4
