_target_: src.model.model.pvae_model
_partial_: true
decoder:
  _target_: flax.nnx.Linear
  in_features: 512
  out_features: 256
  rngs:
    _target_: flax.nnx.Rngs
    default: 1234
  use_bias: false
prior:
  _target_: src.model.model.PVaePrior
  z_dim: 512
  rngs:
    _target_: flax.nnx.Rngs
    default: 5678
scale: 1
